version: "3.7"

services:
  postgres:
    image: postgres:11.4
    environment:
      - POSTGRES_DB
    ports:
      - 5432:5432
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL
      - JWT_KEY
    depends_on:
      - postgres
